import { createServer } from "miragejs";

createServer({
  routes() {
    this.namespace = "api";

    let products = {
      TrueWirelessEarbuds: [
        {
          id: 1,
          name: "boAt Airdropes 131",
          image: "/images/wirelessEarbuds/boAtAirdropes131.jpg",
          category: "TrueWirelessEarbuds",
          categoryName: "True Wireless Earbuds",
          categoryImage: "/category/wirelessEarbirds.webp",
          subCategory: "True Wireless Earbuds",
          color: "Purple",
          playback: "60",
          bestfor: "Travel",
          mvp: "60 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "BestSeller",
          price: 849,
          orignalPrice: 2990,
          rating: 4.8,
          sales: 1447,
          qty: 1,
        },
        {
          id: 2,
          name: "boAt Airdropes 161",
          image: "/images/wirelessEarbuds/boAtAirdropes161.jpg",
          category: "TrueWirelessEarbuds",
          categoryName: "True Wireless Earbuds",
          categoryImage: "/category/wirelessEarbirds.webp",
          subCategory: "True Wireless Earbuds",
          color: "Blue",
          playback: "40",
          bestfor: "Travel",
          mvp: "40 Hours Playback",
          mvp2: "IWP Technology",
          price: 949,
          orignalPrice: 2490,
          bestSeller: "",
          rating: 4.8,
          sales: 439,
          qty: 1,
        },
        {
          id: 3,
          name: "boAt Airdropes 141 ANC",
          image: "/images/wirelessEarbuds/boAtAirdropes141ANC.jpg",
          category: "TrueWirelessEarbuds",
          categoryName: "True Wireless Earbuds",
          categoryImage: "/category/wirelessEarbirds.webp",
          subCategory: "True Wireless Earbuds",
          color: "Gray",
          playback: "80",
          bestfor: "Travel",
          mvp: "Noice Cancellation",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1199,
          orignalPrice: 5990,
          rating: 4.7,
          sales: 34,
          qty: 1,
        },
        {
          id: 4,
          name: "boAt Airdropes 800",
          image: "/images/wirelessEarbuds/boAtAirdropes800.jpg",
          category: "TrueWirelessEarbuds",
          categoryName: "True Wireless Earbuds",
          categoryImage: "/category/wirelessEarbirds.webp",
          subCategory: "True Wireless Earbuds",
          color: "Black",
          playback: "100",
          bestfor: "Music Lovers",
          mvp: "Dolby Audio",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1599,
          orignalPrice: 6490,
          rating: 4.7,
          sales: 102,
          qty: 1,
        },
        {
          id: 5,
          name: "boAt Airdropes ProGear",
          image: "/images/wirelessEarbuds/boAtAirdropesProGear.jpg",
          category: "TrueWirelessEarbuds",
          categoryName: "True Wireless Earbuds",
          categoryImage: "/category/wirelessEarbirds.webp",
          subCategory: "True Wireless Earbuds",
          color: "Green",
          playback: "100",
          bestfor: "Music Lovers",
          mvp: "100 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1799,
          orignalPrice: 6990,
          rating: 4.7,
          sales: 26,
          qty: 1,
        },
        {
          id: 6,
          name: "boAt Airdropes Supreme",
          image: "/images/wirelessEarbuds/boAtAirdropesSupreme.jpg",
          category: "TrueWirelessEarbuds",
          categoryName: "True Wireless Earbuds",
          categoryImage: "/category/wirelessEarbirds.webp",
          subCategory: "True Wireless Earbuds",
          color: "Black",
          playback: "50",
          bestfor: "Sports",
          mvp: "50 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1399,
          orignalPrice: 5990,
          rating: 4.8,
          sales: 114,
          qty: 1,
        },
        {
          id: 7,
          name: "boAt Immortal 121",
          image: "/images/wirelessEarbuds/boAtImmortal121.gif",
          category: "TrueWirelessEarbuds",
          categoryName: "True Wireless Earbuds",
          categoryImage: "/category/wirelessEarbirds.webp",
          subCategory: "Gaming Earbuds",
          color: "Black",
          playback: "40",
          bestfor: "Gaming",
          mvp: "40 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 2199,
          orignalPrice: 4490,
          rating: 4.8,
          sales: 51,
          qty: 1,
        },
        {
          id: 8,
          name: "boAt Immortal 128",
          image: "/images/wirelessEarbuds/boAtImmortal128.gif",
          category: "TrueWirelessEarbuds",
          categoryName: "True Wireless Earbuds",
          categoryImage: "/category/wirelessEarbirds.webp",
          subCategory: "Gaming Earbuds",
          color: "Black",
          playback: "40",
          bestfor: "Gaming",
          mvp: "40 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 2499,
          orignalPrice: 4890,
          rating: 4.8,
          sales: 12,
          qty: 1,
        },
        {
          id: 9,
          name: "boAt Airdopes 115",
          image: "/images/wirelessEarbuds/boAtAirdopes115.webp",
          category: "TrueWirelessEarbuds",
          categoryName: "True Wireless Earbuds",
          categoryImage: "/category/wirelessEarbirds.webp",
          subCategory: "True Wireless Earbuds",
          color: "Red",
          playback: "130",
          bestfor: "Sports",
          mvp: "130 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1899,
          orignalPrice: 2990,
          rating: 4.9,
          sales: 106,
          qty: 1,
        },
      ],
      Neckbands: [
        {
          id: 11,
          name: "boAt Rockerz 261 Pro",
          image: "/images/wirelessEarphones/boAtRocerz261Pro.webp",
          category: "Neckbands",
          categoryName: "Neckbands",
          categoryImage: "/category/neckbands.png",
          subCategory: "True Wireless Earphones",
          color: "Black",
          playback: "15",
          bestfor: "Travel",
          mvp: "Blutooth v5.3",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1749,
          orignalPrice: 5999,
          rating: 4.5,
          sales: 4,
          qty: 1,
        },
        {
          id: 12,
          name: "boAt Rockerz 238 Pro",
          image: "/images/wirelessEarphones/boatRockerz238Pro.webp",
          category: "Neckbands",
          categoryName: "Neckbands",
          categoryImage: "/category/neckbands.png",
          subCategory: "True Wireless Earphones",
          color: "Sky Blue",
          playback: "20",
          bestfor: "Travel",
          mvp: "Blutooth v5.3",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1599,
          orignalPrice: 1999,
          rating: 4.8,
          sales: 13,
          qty: 1,
        },
        {
          id: 13,
          name: "boAt Rockerz 255 ANC",
          image: "/images/wirelessEarphones/boAtRockerz255ANC.webp",
          category: "Neckbands",
          categoryName: "Neckbands",
          categoryImage: "/category/neckbands.png",
          subCategory: "Gaming Neckbands",
          color: "Pink",
          playback: "100",
          bestfor: "Gaming",
          mvp: "100 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1899,
          orignalPrice: 6990,
          rating: 5.0,
          sales: 46,
          qty: 1,
        },
        {
          id: 14,
          name: "boAt Rockerz 258 Pro+",
          image: "/images/wirelessEarphones/boAtRockerz258Pro+.webp",
          category: "Neckbands",
          categoryName: "Neckbands",
          categoryImage: "/category/neckbands.png",
          subCategory: "True Wireless Earphones",
          color: "Music Lovers",
          playback: "40",
          bestfor: "Travel",
          mvp: "40 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1939,
          orignalPrice: 3990,
          rating: 4.6,
          sales: 30,
          qty: 1,
        },
        {
          id: 15,
          name: "boAt Rockerz 300",
          image: "/images/wirelessEarphones/boAtRockerz300.webp",
          category: "Neckbands",
          categoryName: "Neckbands",
          categoryImage: "/category/neckbands.png",
          subCategory: "True Wireless Earphones",
          color: "Yello",
          playback: "30",
          bestfor: "Sports",
          mvp: "30 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1299,
          orignalPrice: 2990,
          rating: 4.8,
          sales: 267,
          qty: 1,
        },
        {
          id: 16,
          name: "boAt Rockerz 333",
          image: "/images/wirelessEarphones/boAtRockerz333.webp",
          category: "Neckbands",
          categoryName: "Neckbands",
          categoryImage: "/category/neckbands.png",
          subCategory: "True Wireless Earphones",
          color: "Red",
          playback: "30",
          bestfor: "Workout",
          mvp: "30 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1499,
          orignalPrice: 3990,
          rating: 4.9,
          sales: 192,
          qty: 1,
        },
        {
          id: 17,
          name: "boAt Rockerz 378",
          image: "/images/wirelessEarphones/boAtRockerz378.webp",
          category: "Neckbands",
          categoryName: "Neckbands",
          categoryImage: "/category/neckbands.png",
          subCategory: "Gaming Neckbands",
          color: "Blue",
          playback: "25",
          bestfor: "Gaming",
          mvp: "25 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1799,
          orignalPrice: 2990,
          rating: 4.9,
          sales: 17,
          qty: 1,
        },
        {
          id: 18,
          name: "boAt Rockerz bliss",
          image: "/images/wirelessEarphones/boAtRockerzbliss.webp",
          category: "Neckbands",
          categoryName: "Neckbands",
          categoryImage: "/category/neckbands.png",
          subCategory: "True Wireless Earphones",
          color: "White",
          playback: "30",
          bestfor: "Spotrs",
          mvp: "30 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1399,
          orignalPrice: 3990,
          rating: 4.8,
          sales: 9,
          qty: 1,
        },
        {
          id: 19,
          name: "boAt Rockerz Summit",
          image: "/images/wirelessEarphones/boAtRockerzSummit.webp",
          category: "Neckbands",
          categoryName: "Neckbands",
          categoryImage: "/category/neckbands.png",
          subCategory: "True Wireless Earphones",
          color: "Blue",
          playback: "30",
          bestfor: "Music Lovers",
          mvp: "30 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 4490,
          orignalPrice: 5690,
          rating: 4.5,
          sales: 4,
          qty: 1,
        },
      ],
      SmartWatches: [
        {
          id: 21,
          name: "boAt Enigma Gem",
          image: "/images/smartWatches/boAtEnigmaGem.jpg",
          category: "SmartWatches",
          categoryName: "Smart Watches",
          categoryImage: "/category/smartwatches.webp",
          subCategory: "Smart Watch",
          color: "Brown",
          playback: "60",
          bestfor: "Formals",
          mvp: "AMOLED Display",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 2999,
          orignalPrice: 8499,
          rating: 4.9,
          sales: 439,
          qty: 1,
        },
        {
          id: 22,
          name: "boAt Strom Call 3",
          image: "/images/smartWatches/boAtStromCall3.jpg",
          category: "SmartWatches",
          categoryName: "Smart Watches",
          categoryImage: "/category/smartwatches.webp",
          subCategory: "Smart Watch",
          color: "Silver",
          playback: "70",
          bestfor: "Formals",
          mvp: "AMOLED Display",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1399,
          orignalPrice: 8499,
          rating: 4.7,
          sales: 17,
          qty: 1,
        },
        {
          id: 23,
          name: "boAt Wave Fury",
          image: "/images/smartWatches/boAtWaveFury.webp",
          category: "SmartWatches",
          categoryName: "Smart Watches",
          categoryImage: "/category/smartwatches.webp",
          subCategory: "Android",
          color: "Pink",
          playback: "60",
          bestfor: "Sports",
          mvp: "AMOLED Display",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1399,
          orignalPrice: 6999,
          rating: 4.9,
          sales: 14,
          qty: 1,
        },
        {
          id: 24,
          name: "boAt Wave Sigma",
          image: "/images/smartWatches/boAtWaveSigma.webp",
          category: "SmartWatches",
          categoryName: "Smart Watches",
          categoryImage: "/category/smartwatches.webp",
          subCategory: "Android",
          color: "Gray",
          playback: "60",
          bestfor: "Sports",
          mvp: "AMOLED Display",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1599,
          orignalPrice: 7499,
          rating: 4.8,
          sales: 11,
          qty: 1,
        },
        {
          id: 25,
          name: "boAt Strom Plus",
          image: "/images/smartWatches/boAtStromPlus.webp",
          category: "SmartWatches",
          categoryName: "Smart Watches",
          categoryImage: "/category/smartwatches.webp",
          subCategory: "Smart Watch",
          color: "Black",
          playback: "60",
          bestfor: "Sports",
          mvp: "AMOLED Display",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1799,
          orignalPrice: 8999,
          rating: 4.9,
          sales: 439,
          qty: 1,
        },
        {
          id: 26,
          name: "boAt Ultima Regal",
          image: "/images/smartWatches/boATUltimaRegal.jpg",
          category: "SmartWatches",
          categoryName: "Smart Watches",
          categoryImage: "/category/smartwatches.webp",
          subCategory: "Smart Watch",
          color: "White",
          playback: "60",
          bestfor: "Sports",
          mvp: "AMOLED Display",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 3099,
          orignalPrice: 9999,
          rating: 4.3,
          sales: 3,
          qty: 1,
        },
        {
          id: 27,
          name: "boAt Wave Primia Talk",
          image: "/images/smartWatches/boAtWavePrimiaTalk.webp",
          category: "SmartWatches",
          categoryName: "Smart Watches",
          categoryImage: "/category/smartwatches.webp",
          subCategory: "Smart Watch",
          color: "Blue",
          playback: "60",
          bestfor: "Sports",
          mvp: "AMOLED Display",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 2499,
          orignalPrice: 10999,
          rating: 4.8,
          sales: 9,
          qty: 1,
        },
        {
          id: 28,
          name: "boAt Enigma X600",
          image: "/images/smartWatches/boAtEnigmaX600.webp",
          category: "SmartWatches",
          categoryName: "Smart Watches",
          categoryImage: "/category/smartwatches.webp",
          subCategory: "Smart Watch",
          color: "Red",
          playback: "60",
          bestfor: "Sports",
          mvp: "AMOLED Display",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 3799,
          orignalPrice: 12999,
          rating: 4.7,
          sales: 6,
          qty: 1,
        },
        {
          id: 29,
          name: "boAt Xtend Plus",
          image: "/images/smartWatches/boAtXtendPlus.webp",
          category: "SmartWatches",
          categoryName: "Smart Watches",
          categoryImage: "/category/smartwatches.webp",
          subCategory: "Smart Watch",
          color: "Blue",
          playback: "60",
          bestfor: "Sports",
          mvp: "AMOLED Display",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1799,
          orignalPrice: 8999,
          rating: 4.7,
          sales: 13,
          qty: 1,
        },
      ],
      WirelessHeadphones: [
        {
          id: 31,
          name: "boAt Rockerz 450 Pro",
          image: "/images/wirelessHeadphones/boAtRockerz450Pro.webp",
          category: "WirelessHeadphones",
          categoryName: "Wireless Headphones",
          categoryImage: "/category/wirelessheadphones.webp",
          subCategory: "True Wireless Headphones",
          color: "Cream",
          playback: "70",
          bestfor: "Travel",
          mvp: "70 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 2099,
          orignalPrice: 3990,
          rating: 4.7,
          sales: 74,
          qty: 1,
        },
        {
          id: 32,
          name: "boAt Rockerz 550 FM",
          image: "/images/wirelessHeadphones/boAtRockerz550FM.avif",
          category: "WirelessHeadphones",
          categoryName: "Wireless Headphones",
          categoryImage: "/category/wirelessheadphones.webp",
          subCategory: "True Wireless Headphones",
          color: "Red",
          playback: "20",
          bestfor: "Travel",
          mvp: "20 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 4999,
          orignalPrice: 5999,
          rating: 5.0,
          sales: 3,
          qty: 1,
        },
        {
          id: 33,
          name: "boAt Rockerz 551 ANC Pro",
          image: "/images/wirelessHeadphones/boAtRockerz551ANCPro.webp",
          category: "WirelessHeadphones",
          categoryName: "Wireless Headphones",
          categoryImage: "/category/wirelessheadphones.webp",
          subCategory: "True Wireless Headphones",
          color: "Blue",
          playback: "72",
          bestfor: "Travel",
          mvp: "72 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 3999,
          orignalPrice: 9990,
          rating: 4.8,
          sales: 74,
          qty: 1,
        },
        {
          id: 34,
          name: "boAt Rockerz 425",
          image: "/images/wirelessHeadphones/boAtRockerz425.avif",
          category: "WirelessHeadphones",
          categoryName: "Wireless Headphones",
          categoryImage: "/category/wirelessheadphones.webp",
          subCategory: "True Wireless Headphones",
          color: "Red",
          playback: "25",
          bestfor: "Travel",
          mvp: "25 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1499,
          orignalPrice: 2990,
          rating: 4.9,
          sales: 26,
          qty: 1,
        },
        {
          id: 35,
          name: "boAt Rockerz 430",
          image: "/images/wirelessHeadphones/boAtRockerz430.webp",
          category: "WirelessHeadphones",
          categoryName: "Wireless Headphones",
          categoryImage: "/category/wirelessheadphones.webp",
          subCategory: "True Wireless Headphones",
          color: "Blue",
          playback: "70",
          bestfor: "Travel",
          mvp: "70 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1299,
          orignalPrice: 2490,
          rating: 4.3,
          sales: 4,
          qty: 1,
        },
        {
          id: 36,
          name: "boAt Rockerz 480",
          image: "/images/wirelessHeadphones/boAtRockerz480.webp",
          category: "WirelessHeadphones",
          categoryName: "Wireless Headphones",
          categoryImage: "/category/wirelessheadphones.webp",
          subCategory: "True Wireless Headphones",
          color: "Gray",
          playback: "60",
          bestfor: "Travel",
          mvp: "60 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1799,
          orignalPrice: 3790,
          rating: 4.3,
          sales: 4,
          qty: 1,
        },
        {
          id: 37,
          name: "boAt Rockid Rush",
          image: "/images/wirelessHeadphones/boAtRockidRush.webp",
          category: "WirelessHeadphones",
          categoryName: "Wireless Headphones",
          categoryImage: "/category/wirelessheadphones.webp",
          subCategory: "True Wireless Headphones",
          color: "Blue",
          playback: "10",
          bestfor: "Travel",
          mvp: "10 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1499,
          orignalPrice: 2490,
          rating: 4.5,
          sales: 78,
          qty: 1,
        },
        {
          id: 38,
          name: "Rockerz 450 POLO",
          image: "/images/wirelessHeadphones/Rockerz 450 POLO.avif",
          category: "WirelessHeadphones",
          categoryName: "Wireless Headphones",
          categoryImage: "/category/wirelessheadphones.webp",
          subCategory: "True Wireless Headphones",
          color: "Black",
          playback: "20",
          bestfor: "Travel",
          mvp: "20 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1899,
          orignalPrice: 3990,
          rating: 4.8,
          sales: 273,
          qty: 1,
        },
        {
          id: 39,
          name: "boAt Rockerz 650",
          image: "/images/wirelessHeadphones/boAtRockerz650SunburnEdition.avif",
          category: "WirelessHeadphones",
          categoryName: "Wireless Headphones",
          categoryImage: "/category/wirelessheadphones.webp",
          subCategory: "True Wireless Headphones",
          color: "Yello",
          playback: "70",
          bestfor: "Travel",
          mvp: "70 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1999,
          orignalPrice: 4999,
          rating: 4.9,
          sales: 23,
          qty: 1,
        },
      ],
      WirelessSpeakers: [
        {
          id: 41,
          name: "boAt Stone 180",
          image: "/images/wirelessSpeakers/boAtStone180.jpg",
          category: "WirelessSpeakers",
          categoryName: "Wireless Speakers",
          categoryImage: "/category/wirelessspeakers.webp",
          subCategory: "Wireless Speakers",
          color: "Blue",
          playback: "08",
          bestfor: "Travel",
          mvp: "08 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1299,
          orignalPrice: 2490,
          rating: 4.8,
          sales: 27,
          qty: 1,
        },
        {
          id: 42,
          name: "boAt Stone 358 Pro",
          image: "/images/wirelessSpeakers/boAtStone358Pro.jpg",
          category: "WirelessSpeakers",
          categoryName: "Wireless Speakers",
          categoryImage: "/category/wirelessspeakers.webp",
          subCategory: "Wireless Speakers",
          color: "Gray",
          playback: "12",
          bestfor: "Travel",
          mvp: "12 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1999,
          orignalPrice: 4990,
          rating: 5.0,
          sales: 1,
          qty: 1,
        },
        {
          id: 43,
          name: "boAt Stone Spinx Pro",
          image: "/images/wirelessSpeakers/boAtStoneSpinxPro.jpg",
          category: "WirelessSpeakers",
          categoryName: "Wireless Speakers",
          categoryImage: "/category/wirelessspeakers.webp",
          subCategory: "Wireless Speakers",
          color: "Black",
          playback: "08",
          bestfor: "Travel",
          mvp: "8 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 2499,
          orignalPrice: 9999,
          rating: 4.8,
          sales: 56,
          qty: 1,
        },
        {
          id: 44,
          name: "boAt Party Pal 195",
          image: "/images/wirelessSpeakers/boAtPartyPal195.webp",
          category: "WirelessSpeakers",
          categoryName: "Wireless Speakers",
          categoryImage: "/category/wirelessspeakers.webp",
          subCategory: "Party Speakers",
          color: "Black",
          playback: "06",
          bestfor: "Party",
          mvp: "06 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 5999,
          orignalPrice: 17990,
          rating: 4.8,
          sales: 5,
          qty: 1,
        },
        {
          id: 45,
          name: "boAt Stone 350",
          image: "/images/wirelessSpeakers/boAtStone350DeadpoolEdition.webp",
          category: "WirelessSpeakers",
          categoryName: "Wireless Speakers",
          categoryImage: "/category/wirelessspeakers.webp",
          subCategory: "Wireless Speakers",
          color: "Purple",
          playback: "12",
          bestfor: "Travel",
          mvp: "12 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1549,
          orignalPrice: 3490,
          rating: 4.9,
          sales: 10,
          qty: 1,
        },
        {
          id: 46,
          name: "boAt Stone 352 Pro",
          image: "/images/wirelessSpeakers/boAtStone352Pro.jpg",
          category: "WirelessSpeakers",
          categoryName: "Wireless Speakers",
          categoryImage: "/category/wirelessspeakers.webp",
          subCategory: "Wireless Speakers",
          color: "Blue",
          playback: "12",
          bestfor: "Travel",
          mvp: "12 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1999,
          orignalPrice: 4990,
          rating: 4.9,
          sales: 9,
          qty: 1,
        },
        {
          id: 47,
          name: "boAt Stone 352",
          image: "/images/wirelessSpeakers/boAtStone352ThorEdition.webp",
          category: "WirelessSpeakers",
          categoryName: "Wireless Speakers",
          categoryImage: "/category/wirelessspeakers.webp",
          subCategory: "Wireless Speakers",
          color: "Blue",
          playback: "12",
          bestfor: "Travel",
          mvp: "12 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1699,
          orignalPrice: 3490,
          rating: 4.8,
          sales: 8,
          qty: 1,
        },
        {
          id: 48,
          name: "boAt Party Pal 63 Pro",
          image: "/images/wirelessSpeakers/boAtPartPal63Pro.webp",
          category: "WirelessSpeakers",
          categoryName: "Wireless Speakers",
          categoryImage: "/category/wirelessspeakers.webp",
          subCategory: "Party Speaker",
          color: "Black",
          playback: "08",
          bestfor: "Party",
          mvp: "08 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 4999,
          orignalPrice: 12990,
          rating: 4.8,
          sales: 10,
          qty: 1,
        },
        {
          id: 49,
          name: "boAt Stone 650",
          image: "/images/wirelessSpeakers/boAtStone650.webp",
          category: "WirelessSpeakers",
          categoryName: "Wireless Speakers",
          categoryImage: "/category/wirelessspeakers.webp",
          subCategory: "Wireless Speakers",
          color: "Purple",
          playback: "7",
          bestfor: "Travel",
          mvp: "07 Hours Playback",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 1899,
          orignalPrice: 4990,
          rating: 4.9,
          sales: 110,
          qty: 1,
        },
      ],
      WiredEarphones: [
        {
          id: 51,
          name: "Bassheads 100C",
          image: "/images/wiredEarphone/Bassheads100C.webp",
          category: "WiredEarphones",
          categoryName: "Wired Earphones",
          categoryImage: "/category/wiredearphones.webp",
          subCategory: "True Wired Earphones",
          color: "Black",
          bestfor: "Travel",
          mvp: "In-Line Microphone",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 599,
          orignalPrice: 1990,
          rating: 5.0,
          sales: 7,
          qty: 1,
        },
        {
          id: 52,
          name: "Bassheads 103",
          image: "/images/wiredEarphone/Bassheads103.webp",
          category: "WiredEarphones",
          categoryName: "Wired Earphones",
          categoryImage: "/category/wiredearphones.webp",
          subCategory: "True Wired Earphones",
          color: "Blue",
          bestfor: "Travel",
          mvp: "In-Line Microphone",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 499,
          orignalPrice: 1290,
          rating: 4.8,
          sales: 638,
          qty: 1,
        },
        {
          id: 53,
          name: "Bassheads 122",
          image: "/images/wiredEarphone/Bassheads122.webp",
          category: "WiredEarphones",
          categoryName: "Wired Earphones",
          categoryImage: "/category/wiredearphones.webp",
          subCategory: "True Wired Earphones",
          color: "Black",
          bestfor: "Travel",
          mvp: "In-Line Microphone",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 499,
          orignalPrice: 1290,
          rating: 5.0,
          sales: 7,
          qty: 1,
        },
        {
          id: 54,
          name: "Bassheads 162v2",
          image: "/images/wiredEarphone/Bassheads162v2.webp",
          category: "WiredEarphones",
          categoryName: "Wired Earphones",
          categoryImage: "/category/wiredearphones.webp",
          subCategory: "True Wired Earphones",
          color: "White",
          bestfor: "Travel",
          mvp: "In-Line Microphone",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 399,
          orignalPrice: 990,
          rating: 5.0,
          sales: 2,
          qty: 1,
        },
        {
          id: 55,
          name: "Bassheads 172",
          image: "/images/wiredEarphone/Bassheads172.jpg",
          category: "WiredEarphones",
          categoryName: "Wired Earphones",
          categoryImage: "/category/wiredearphones.webp",
          subCategory: "True Wired Earphones",
          color: "Red",
          bestfor: "Travel",
          mvp: "In-Line Microphone",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 399,
          orignalPrice: 1290,
          rating: 4.8,
          sales: 137,
          qty: 1,
        },
        {
          id: 56,
          name: "Bassheads 225",
          image: "/images/wiredEarphone/Bassheads225.webp",
          category: "WiredEarphones",
          categoryName: "Wired Earphones",
          categoryImage: "/category/wiredearphones.webp",
          subCategory: "True Wired Earphones",
          color: "Orange",
          bestfor: "Travel",
          mvp: "In-Line Microphone",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 699,
          orignalPrice: 990,
          rating: 5.0,
          sales: 22,
          qty: 1,
        },
        {
          id: 57,
          name: "boAt Bassheads 104",
          image: "/images/wiredEarphone/boAtBassheads104.webp",
          category: "WiredEarphones",
          categoryName: "Wired Earphones",
          categoryImage: "/category/wiredearphones.webp",
          subCategory: "True Wired Earphones",
          color: "Blue",
          bestfor: "Travel",
          mvp: "In-Line Microphone",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 299,
          orignalPrice: 999,
          rating: 4.7,
          sales: 106,
          qty: 1,
        },
        {
          id: 58,
          name: "boAt Bassheads 122 ANC",
          image: "/images/wiredEarphone/boAtBassheads122ANC.webp",
          category: "WiredEarphones",
          categoryName: "Wired Earphones",
          categoryImage: "/category/wiredearphones.webp",
          subCategory: "True Wired Earphones",
          color: "Black",
          bestfor: "Travel",
          mvp: "In-Line Microphone",
          mvp2: "IWP Technology",
          bestSeller: "",
          price: 999,
          orignalPrice: 2999,
          rating: 4.9,
          sales: 8,
          qty: 1,
        },
      ],
    };

    // Route for all products
    this.get("/products", () => {
      return products;
    });

    // Route for fetching products by category
    this.get("/products/:category", (schema, request) => {
      let category = request.params.category;
      return products[category]
        ? products[category]
        : { error: "Category not found" };
    });

    // Route for fetching a single product by ID
    this.get("/product/:id", (schema, request) => {
      let id = Number(request.params.id);
      let allProducts = Object.values(products).flat();
      let product = allProducts.find((p) => p.id === id);
      return product ? product : { error: "Product not found" };
    });
  },
});
